// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaIKH-vgEb_toipf-RkaHrud_LcSptn2s',
    appId: '1:689406118129:web:e6cbe4d6507e7b88dd0150',
    messagingSenderId: '689406118129',
    projectId: 'sos-assist-0001',
    authDomain: 'sos-assist-0001.firebaseapp.com',
    storageBucket: 'sos-assist-0001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFKa4Oo_VCSFOhwzj_igu50tbcvyCn5qQ',
    appId: '1:689406118129:android:4346aa21c685a5a2dd0150',
    messagingSenderId: '689406118129',
    projectId: 'sos-assist-0001',
    storageBucket: 'sos-assist-0001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAh9T5OBZhgERlwH7hdEpTx_X4ANif9c0',
    appId: '1:689406118129:ios:478702f2a7ca739bdd0150',
    messagingSenderId: '689406118129',
    projectId: 'sos-assist-0001',
    storageBucket: 'sos-assist-0001.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAh9T5OBZhgERlwH7hdEpTx_X4ANif9c0',
    appId: '1:689406118129:ios:7239532c1d8e0a34dd0150',
    messagingSenderId: '689406118129',
    projectId: 'sos-assist-0001',
    storageBucket: 'sos-assist-0001.appspot.com',
    iosBundleId: 'com.example.mobileApp.RunnerTests',
  );
}
